PURPOSE="11814"
LOCATION="westeurope"
RG_NAME="rg-aks-"$PURPOSE
CLUSTER_NAME="aks-"$PURPOSE
MY_HOME_PUBLIC_IP=$(curl ifconfig.io)

WIN_VM_SUBNET_NAME="rdc-client"
WIN_VM_SNET_CIDR="10.0.7.0/28"
WIN_VM_PRIV_IP="10.0.7.4/32"
## Windows Settings
WINDOWS_ADMIN_USER=$ADMIN_USERNAME
## Windows nodes settings
WINDOWS_NODE_POOL_NAME="npwin"
WINDOWS_NODE_POOL_NUMBER="1"
## Public IP name Windows
WIN_VM_PUBLIC_IP_NAME="rdcclientpublicip"
WIN_VM_DEFAULT_IP_CONFIG="ipconfig1"
## VM Windows Jump Server
WIN_RG_LOCATION=$LOCATION
WIN_VM_NAME="rdcclient-"$PURPOSE
WIN_VM_INTERNAL_NAME="rdcclient-"$PURPOSE
WIN_IMAGE_PROVIDER="MicrosoftWindowsServer"
WIN_IMAGE_OFFER="WindowsServer"
WIN_IMAGE_SKU="2019-Datacenter"
WIN_IMAGE_VERSION="latest"
WIN_IMAGE="$WIN_IMAGE_PROVIDER:$WIN_IMAGE_OFFER:$WIN_IMAGE_SKU:$WIN_IMAGE_VERSION"
WIN_PUBLIC_IP=""
WIN_VNET_NAME=$AKS_VNET
WIN_VNET_SUBNET_NAME="rdc-client"
#WIN_VM_SIZE="Standard_D2s_v3"
WIN_VM_SIZE="Standard_D4s_v3"
WIN_VM_STORAGE_SKU="Standard_LRS"
WIN_VM_OS_DISK_SIZE="130"
WIN_VM_OS_DISK_NAME="$WIN_VM_NAME""_disk_01"
WIN_VM_NSG_NAME="$WIN_VM_NAME""_nsg"
WIN_VM_NIC_NAME="$WIN_VM_NAME""nic01"
WIN_TAGS="env=kubernetes"
